### PR TITLE
Hot wallet issue

### PR DESCRIPTION
**Pull request by anandsinghparihar**
https://particl.atlassian.net/browse/PAR-213
https://particl.atlassian.net/browse/PAR-216

### CODE REVIEW

**Comment by kewde** [comment]
Check with dasource if this is still relevant, I think we might strip out the hot wallet code :question:

**Comment by dasource** [comment]
Suggestion changes:

1. Remove Hot Wallet modal.
2. Change the snow flake icon so it is
a. gray when cold staking is disabled
b. blue when cold staking is enabled
3. On Hover just display status.

That should be all.

**Comment by anandsinghparihar** [comment]
Okay Thank I'll do that

**Comment by anandsinghparihar** [comment]
please close this PR . @allienworks  is working on 
Suggestion changes:
Remove Hot Wallet modal.
Change the snow flake icon so it is
a. gray when cold staking is disabled
b. blue when cold staking is enabled
On Hover just display status.

**Comment by allienworks** [comment]
No, why would we close this PR? Doesn't make sense.

@anandsinghparihar I can remove the modal, but the rest (snowflake icon change + displaying status on hover) I can't do. Please do those changes.

**Comment by anandsinghparihar** [comment]
Okay

**Comment by anandsinghparihar** [comment]
Cherrypick this changes into new branch.

**Pull request closed without merging**
