### PR TITLE
GFX updates

### PR DESCRIPTION
**Pull request by gerlofvanek**
**GFX:**
- [x] Testnet logo
- [x] Add new updated .SVG icons + logic naming
- [x] Include new send(out)/receive(in) icons
- [x] First page and last page icon, include copy paste icon, include debug-console icon, and other various icons
- [x] Include currency icons: USD, YEN, EURO, POUND. 
- [x] Include cryptocurrency icons: PARTICL (WIP), BITCOIN
- [x] Convert icons in single .ttf file

**PRG:**

**@pciavald**  #353 
-  if testnet replace sidebar logo particl-logo.svg -> particl-logo-testnet.svg
- If testnet add "- testnet" in application title 
- If testnet use testnet blockexplorer url (explorer-testnet.particl.io), if mainnet use mainet url blockexplorer (explorer.particl.io)

- [X]  Update all icons .class with logic naming

**PREVIEW + ICONS .CLASS NAMES:**

### CODE REVIEW

**Comment by allienworks** [comment]
Sweet icons you've got there @gerlofvanek! I particularly like the "devilish" Particl with horns :]

**Comment by anandsinghparihar** [comment]
let me check

**Comment by vikas-cis** [comment]
Seems working for me 👍

**Comment by anandsinghparihar** [comment]
Seems working for linux

**Pull request merged**
