### PR TITLE
error handeling of words entered - REBASE

### PR DESCRIPTION
**Pull request by EagleEye25**
Rebased onto restructure: 

If user enters an invalid word it will be displayed in red, if a valid word is entered, but not correct to the generated words and next is clicked an appropriate error message will be shown

### CODE REVIEW

**Comment by pciavald** [comment]
Please always include a thorough description for the reviewer to know what he's reviewing

**Comment by HenkSwardt** [comment]
Hi @pciavald 

Updated description of issue

**Comment by pciavald** [comment]
Seems good but i have these buttons displaying : 
screenshot_20171204_194221

**Comment by kewde** [comment]
The buttons is due to the use of the md- tag, should be using mat-.

I had exactly the same issue on the restructure branch.

**Comment by kewde** [comment]
Solved conflicts.

**Comment by kewde** [comment]
Seems like I already had these changes from dev?

**Pull request closed without merging**
