### PR TITLE
added alerts for cold staking

### PR DESCRIPTION
**Pull request by EagleEye25**
*enabled unlock for staking, while cold staking in progress
*edited messages for if wallet is locked, unlocked in cold staking message

### CODE REVIEW

**Comment by EagleEye25** [comment]
ss 2017-12-18 at 01 52 50
ss 2017-12-18 at 01 52 30

**Comment by EagleEye25** [comment]
ss 2017-12-19 at 10 11 19
ss 2017-12-19 at 10 11 07

**Comment by kapsr** [comment]
"Unitl" and "Pasued" need spelling correction

**Comment by allienworks** [comment]
- fixed some typos
- tweaked the styling, reworked the layout a bit

But I can't test it properly. My wallet isn't encrypted (so not even locked) and I'm still getting "Cold staking paused - wallet locked" error.. Can someone confirm this? Is wallet encryption necessary for cold staking?

**Comment by EagleEye25** [comment]
think this is looking good
ss 2017-12-21 at 09 12 46
ss 2017-12-21 at 09 12 33

**Comment by vikas-cis** [comment]
I have tested it and looks good to me 👍

**Comment by pciavald** [comment]
Can't test this. I merged dev (couldn't compile otherwise), the modal to activate cold staking is broken. #547

**Comment by pciavald** [comment]
## GFX problem
screenshot_20171227_165400

## vocabulary or PRG problem
My wallet is unlocked (not just for staking) and it says it is locked and should be unlocked *for staking* which it is, but not only.
screenshot_20171227_165613

**Comment by pciavald** [comment]
Can you also link the alerts to the desktop notifications ? it would be best to have desktop notifications about staking node having progress or finished as the process is long so you won't be looking at it all the time.

**Comment by pciavald** [comment]
I used the christmas holiday to set up my cold staking and test the functionnality, and there's a problem in the logic.

### case 1
- start wallet : wallet is locked and cold staking status needs unlock
- unlock wallet for staking only : cold staking status is not shown and needs unlock

### case 2
- start wallet : wallet is locked and cold staking status needs unlock
- fully unlock wallet : cold staking status is unlocked but states that the cold staking is paused because wallet is locked (which is wrong)

### case 3
- start wallet : wallet is locked and cold staking status needs unlock
- unlock cold staking : fully unlocks wallet, cold staking states that wallet is locked (wrong)

### only way to make it work currently : 
- start wallet : wallet is locked and cold staking status needs unlock
- unlock cold staking
- lock wallet
- unlock wallet for staking only

### expected behaviour 1
- start wallet
- unlock cold staking
- wallet is unlocked for staking only and states the cold staking status as active

### expected behaviour 2
- start wallet
- fully unlock wallet
- wallet is fully unlocked and states the cold staking status as active

### expected behaviour 3
- start wallet
- unlock wallet for staking only
- wallet is unlocked for staking only and states the cold staking status as active

**Comment by allienworks** [comment]
- merged in latest changes from `dev`
- fixed cold staking widget GFX issue

**Comment by pciavald** [comment]
So right now I'm not getting the same behaviour, which is partly fixed but I wonder why....

### case 1 : still true

**unlock wallet for staking only : cold staking status is not shown and needs unlock**

peek 2018-01-04 13-24

### case 2 : resolved ?

**fully unlock wallet : unlocks cold staking and activates it, that's what we expect... it used to unlock it and say `Paused`**

peek 2018-01-04 13-25

### case 3 : partly resolved

**unlock cold staking widget : should unlock wallet for staking only instead of fully unlock**

peek 2018-01-04 13-29

**Comment by pciavald** [comment]
@anandsinghparihar @vikas-cis let's pause this task, it will be redifined

**Pull request merged**
