### PR TITLE
slow block confirmation updated fix

### LINKED ISSUE #663: transactions in overview update too slow
transaction confirmations in overview update at a too slow rate, i had 4 confirmations in block explorer before seeing them in overview

### PR DESCRIPTION
**Pull request by vikas-cis**
#663

### CODE REVIEW

**Comment by pciavald** [comment]
Confirmations now work, but unexpectedly transactions now appear in reverse order !

screenshot_20180115_231258

**Comment by vikas-cis** [comment]
@pciavald let me have a look 

Thanks

**Comment by vikas-cis** [comment]
@pciavald I have started with fresh wallet and done some transactions on it but couldn't able to reproduce the issue.
screen shot 2018-01-16 at 3 17 05 pm

**Comment by pciavald** [comment]
idk why, it seems to work now...

**Pull request merged**
