### PR TITLE
RPC: receive tab connection

### PR DESCRIPTION
**Pull request by kewde**

### CODE REVIEW

**Comment by kewde** [comment]
It seems that I can't push to this repo anymore for some odd reason.
Do not forget: push fix for travis

**Comment by kewde** [comment]
Ready for review and testing and possibly merging.

TODO:
display balance by address - needs rpc change or hackish fix.

**Comment by rynomster** [comment]
I am merging this PR for now, but when there are no addresses, it shows "Empty label" and "Empty address" on the receive table. I think it shouldn't show anything in that case.

**Comment by kewde** [comment]
@rynomster that is what I initially tried, but the code would spit out a lot of errors, it couldn't be an undefined value. I might be able to leave it empty ( = '' ).

**Pull request merged**
