### PR TITLE
Input clear button

### PR DESCRIPTION
**Pull request by anandsinghparihar**
Add All search

 Input with a clear button #610 
>> Right now all search input doesn't have a clear button, we need to clear that input by backspace. so I hope we should add clear button.

here is a preview of a clear button : 
input clear button

### CODE REVIEW

**Comment by allienworks** [comment]
I'm honestly not that sure if this is absolutely needed, but OK. Styled.
IMO there are more urgent tasks at hand, so please try to do those first before making up other (not necessary) tasks.

**Comment by anandsinghparihar** [comment]
@allienworks that time I don't have any task ... anyway thanks for your suggestion  :d

**Comment by allienworks** [comment]
@anandsinghparihar I get that. Have a look at the current milestone when you're out of work. There's a lot of stuff needed to be done for the next release (always).

**Comment by anandsinghparihar** [comment]
@allienworks I don't want  argue ask to Henk :)

**Comment by pciavald** [comment]
@anandsinghparihar @allienworks I edited the thread conversations, these matters are better discussed on Matrix 👍 cheers :)

**Comment by anandsinghparihar** [comment]
@pciavald 
> can you please activate escape to clear & enter like in history search
Enter is not required because of all search fire on input changes. I've added escape for clear search field. 

@allienworks now you can work on the design part.

**Comment by allienworks** [comment]
Restyled.

This is how icons are organized now:

- `part-circle-remove` as "close/delete" (for closing modals, deleting entries)
- `part-clear-all` as "clear" (e.g. here for clearing text from inputs or whole forms)
- `part-cross` as "cancel"

I don't think we should unify all those 3 into 1; after all, there are differences between them. Those icons that aren't fixed according to this ^ are fixed already in #657 (FYI).

**Pull request merged**
