### PR TITLE
Wallet auto-lock delay increased to 5 mins

### PR DESCRIPTION
**Pull request by vikas-cis**
#587 
  When the wallet is unlocked we automatically lock it after 30 seconds. This is a security feature to ensure your wallet is not left unlocked and unattended. Please change this delay time to 5 mins (300 sec).

### CODE REVIEW

**Comment by vikas-cis** [comment]
@pciavald i have added timer, can you please have a look 

Thanks

**Comment by vikas-cis** [comment]
@allienworks Can you please check if we need graphical things for the message ?

**Comment by allienworks** [comment]
@vikas-cis may I have one more request? The countdown is now visible even a bit after it reaches 0 (looks like something like `-5:00` flashes there for a fraction of second). Could you hide the countdown ~1 second earlier so this won't happen?

**Comment by allienworks** [comment]
Countdown styled, all known issues fixed. It's neat! :)

**Pull request merged**
