### PR TITLE
Feature/transactions table rework

### PR DESCRIPTION
**Pull request by demyanrogozhin**
* Table layout converted to responsive flexbox layout.
* Added grid component for possible future use.

### CODE REVIEW

**Comment by kewde** [comment]
todo: @gerlofvanek can you make a pretty minus sign? I currently grabbed a random icon hehe.
The day we get rid font awesome icons is the day I'll make a chocolate cake to celebrate :smile:

**Comment by rynomster** [comment]
Looking good :D going to test it properly tonight

**Comment by kewde** [comment]
Once the table is expanded, the icon will disappear, icon is in PR #75, merge that one first to fix.

**Comment by rynomster** [comment]
Merging this one without #75 , will review that shortly. This looks great. good job @demyanrogozhin

**Pull request merged**
