### PR TITLE
Display client/daemon version

### PR DESCRIPTION
**Pull request by allienworks**
- adds client/daemon versions in the bottom of the sidebar
- needs to implement the functionality (dynamically display the correct version numbers)

### CODE REVIEW

**Comment by kewde** [comment]
blocked by #297

**Comment by HenkSwardt** [comment]
both #297 and #335 has been merged, @kewde  Please confirm if this can be merged?

**Comment by allienworks** [comment]
@HenkSwardt it can't be merged yet. This feature is only styled so far, we need someone to implement displaying correct version numbers.

**Comment by HenkSwardt** [comment]
@kewde , please confirm that you are working on the implementation of displaying the correct version number. I see you are assigned to this issue.

**Comment by allienworks** [comment]
@HenkSwardt nobody was officially assigned to this so far.

**Comment by HenkSwardt** [comment]
@allienworks this isse has ben assigned to @kewde for the last week, hence the question I asked yesterday. Why has he been removed as assignee?

Thanks

**Comment by HenkSwardt** [comment]
Hi @EagleEye25 

Please can you look at making this change for us. 

Thank you

**Comment by EagleEye25** [comment]
Has been completed and a pull request has been made for review

**Comment by HenkSwardt** [comment]
https://github.com/particl/partgui/pull/389

**Comment by allienworks** [comment]
@EagleEye25 you could push your changes directly here.. I'm not sure why you did another PR, but OK :)

**Pull request merged**
