### PR TITLE
Md paginator

### PR DESCRIPTION
**Pull request by anandsinghparihar**
https://particl.atlassian.net/browse/PART-44

### CODE REVIEW

**Comment by xludx** [comment]
fix the codeclimate issues

**Comment by anandsinghparihar** [comment]
@xludx all are TODOS please consider it..

**Comment by xludx** [comment]
I can't edit codeclimate checks, but in my opinion todo's could be allowed. I often mark code with a todo to find and fix them later on.

**Comment by rynomster** [comment]
Yes someone from the organisation has to approve the TODOs. I will do it
quickly as soon as I get home with decent internet.

**Pull request merged**
