### PR TITLE
Add "Send all" button/icon to Send page 

### PR DESCRIPTION
**Pull request by anandsinghparihar**
Add "Send all" button/icon to Send page

### CODE REVIEW

**Comment by allienworks** [comment]
GFX LGTM, works nicely even when switching between Public/Private balances.

Haven't reviewed the TS code though.

**Comment by anandsinghparihar** [comment]
this PR is cover: https://github.com/particl/partgui/pull/510

**Comment by allienworks** [comment]
Code got a bit broken (probably due to my Send page redesign) – the "send all" button now dynamically don't change according to which balance is selected. Please fix.

> If you have 100 public coins, only 40 blind, select the public balance and then "send all", it shows correctly 100. But if you then switch to blind, the amount to send is still 100.

Other than that: OK by me.

**Comment by allienworks** [comment]
Works perfectly now, thanks!
After someone approves TS code changes, we can merge.

**Pull request merged**
