### PR TITLE
Send page redesign

### PR DESCRIPTION
**Pull request by allienworks**
- change of base layout for Send page
- reorg of elements/sections for better usability
- some design tweaks (how else ;)
- also added click-through to Overview page from logo

### TODO

- [x] PRG: needs fix for the balance amounts when selecting "from" accounts
- [x] make help text lighter (so more important stuff pops out more)
- [x] remove the verified bg on inputs (?) - it's quite annoying and not really nice at all
- [x] "show advanced button" - tweak GFX, maybe move elsewhere?

### CODE REVIEW

**Comment by vikas-cis** [comment]
@allienworks  I am looking in the PRG stuff what you suggested above

**Comment by allienworks** [comment]
Current preview:

send-redesign

**Comment by pciavald** [comment]
this PR had a linter error, was it corrected ? @gerlofvanek 
`ERROR: /home/travis/build/particl/partgui/src/app/wallet/wallet/send/send.component.ts[77, 84]: trailing whitespace`

**Comment by pciavald** [comment]
just seen #514, sorry.

**Pull request merged**
