### PR TITLE
History tabs

### PR DESCRIPTION
**Pull request by pciavald**
This pull request integrates the filtertransactions API in the History tab to allow fine-grained control on the list's contents.

### CODE REVIEW

**Comment by pciavald** [comment]
waiting for #337

**Comment by allienworks** [comment]
_Suggestion:_ I was thinking about this. The obvious (UI/UX) solution would be to include tabs at the top with "Received / Sent / Staked" etc. However I think it might be better to go a different way and use checkboxes or something like that (to let the user explicitly include or exclude certain type of TXs) – e.g. I might want to see only Sent & Received TXs or Sent & Staked etc. This would give the user more flexibility and options.

**Comment by pciavald** [comment]
@allienworks if you agree I will only to the #PRG side of it, then you style it how you see fit ?

**Comment by allienworks** [comment]
@pciavald sure, that's why I'm here ;)

**Comment by allienworks** [comment]
Outdated, closing (new PR will replace this).

**Pull request closed without merging**
