### PR TITLE
Remove modals dependency from createwallet

### PR DESCRIPTION
**Pull request by kewde**

### CODE REVIEW

**Comment by pciavald** [comment]
tests are not passing, i tried a few ways to fix it but the error message is rather unclear

**Comment by kewde** [comment]
Declaration was missing, added it again

**Comment by pciavald** [comment]
tests still not passing @kewde

**Comment by kewde** [comment]
There will be more failed tests - I re-added the password component. I think there are more components I will have to add manually.

**Comment by rynomster** [comment]
modalService is now used in createWallet to set enableClose.. Once a user has gone past step one they can't close the modal until the complete or go back.

**Pull request closed without merging**
