### PR TITLE
fix wallet "tab" being displayed twice

### PR DESCRIPTION
**Pull request by EagleEye25**
made it so that if the wallet.dat isnt encrypted that the gui will only show the add account button on the sidebar

### CODE REVIEW

**Comment by pciavald** [comment]
very strange, on this branch and even after merging dev in, i have this GFX : 
screenshot_20180105_134105
as opposed to the normal : 
screenshot_20180105_134241

**Comment by pciavald** [comment]
can you check what happens when you start creating a wallet, quit app at the "copy your words" step and launch again ?

**Comment by pciavald** [comment]
i confirm this issue.

screenshot_20180108_134329

**Comment by HenkSwardt** [comment]
Could this and #614 have something in common?

**Comment by allienworks** [comment]
Truly weird behaviour. For some reason another `box-shadow` was added there, not sure why. I've fixed that.

**Pull request merged**
