### PR TITLE
Info/warning for GUI updates

### PR DESCRIPTION
**Pull request by allienworks**
- added notification bar (closes https://github.com/particl/partgui/issues/488, https://github.com/particl/partgui/issues/489)
- green one for infos, updates etc.
- red one for more important stuff

### CODE REVIEW

**Comment by kewde** [comment]
I like this.. Will need a bit of a change in the backend I believe.

**Comment by allienworks** [comment]
(Rebased on top of `dev`)

**Comment by cryptoguard** [comment]
Another cool function would be to be able to push text messages to users. 
i.e. "Don't forget to vote for community proposal #42 before block #50000"

**Comment by pciavald** [comment]
@cryptoguard it's another functionality, maybe open an issue ?

**Comment by pciavald** [comment]
@allienworks buttons logos were lost rebasing dev

**Comment by allienworks** [comment]
Nice work @anandsinghparihar! The notification now shows only when the version on GH is newer than your currently running one.

After code review, this is ready to be merged.

**Comment by pciavald** [comment]
I tried 1.0.1 and 1.0.0 in package.json and i get nothing... am I doing something wrong ?

**Comment by anandsinghparihar** [comment]
@pciavald please try lower value  then `1.0.1` , because current version get from GitHub and its `1.0.1`.

try 
`"version": "0.1.0",`

**Comment by pciavald** [comment]
Hahah, sorry guys, my bad.

**Pull request merged**
